# This is the Nextcloud configuration file optimized for ARM architecture and 1TB file support
# Environment variables are loaded from .env file by default
# See README.md for detailed documentation
#
# This setup includes:
# - Nextcloud web application (ARM-optimized with large file support)
# - PostgreSQL database (ARM-optimized)
# - Redis cache (ARM-optimized with multithreading)

version: "3.8"

services:
  nextcloud:
    image: "nextcloud:latest"
    environment:
      - TZ=${TZ}
      # Database configuration
      - POSTGRES_DB=${NEXTCLOUD_DB_NAME}
      - POSTGRES_USER=${NEXTCLOUD_DB_USER}
      - POSTGRES_PASSWORD=${NEXTCLOUD_DB_PASSWORD}
      - POSTGRES_HOST=nextcloud_db:5432
      # Admin user configuration
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      # Redis configuration
      - REDIS_HOST=nextcloud_redis
      - REDIS_HOST_PASSWORD=${NEXTCLOUD_REDIS_PASSWORD}
      # Trusted domains
      - NEXTCLOUD_TRUSTED_DOMAINS=${DOMAIN_NAME}
      # Data directory
      - NEXTCLOUD_DATA_DIR=/var/www/html/data
      # Reverse proxy configuration
      - OVERWRITEPROTOCOL=https
      - OVERWRITEHOST=${DOMAIN_NAME}
      - TRUSTED_PROXIES=172.16.0.0/12
      # Large file support configuration via environment variables
      - PHP_MEMORY_LIMIT=${PHP_MEMORY_LIMIT:-2G}
      - PHP_UPLOAD_LIMIT=${PHP_UPLOAD_LIMIT:-1024G}
      - PHP_MAX_FILE_UPLOADS=${PHP_MAX_FILE_UPLOADS:-200}
      - PHP_MAX_INPUT_VARS=${PHP_MAX_INPUT_VARS:-10000}
      - PHP_MAX_EXECUTION_TIME=${PHP_MAX_EXECUTION_TIME:-3600}
      - PHP_MAX_INPUT_TIME=${PHP_MAX_INPUT_TIME:-3600}
      - PHP_POST_MAX_SIZE=${PHP_POST_MAX_SIZE:-1024G}
      - APACHE_BODY_LIMIT=${APACHE_BODY_LIMIT:-1073741824000}
      # PHP OPcache optimization for ARM
      - PHP_OPCACHE_ENABLE=${PHP_OPCACHE_ENABLE:-1}
      - PHP_OPCACHE_MEMORY_CONSUMPTION=${PHP_OPCACHE_MEMORY_CONSUMPTION:-256}
      - PHP_OPCACHE_MAX_ACCELERATED_FILES=${PHP_OPCACHE_MAX_ACCELERATED_FILES:-10000}
      - PHP_OPCACHE_REVALIDATE_FREQ=${PHP_OPCACHE_REVALIDATE_FREQ:-1}
      - PHP_OPCACHE_SAVE_COMMENTS=${PHP_OPCACHE_SAVE_COMMENTS:-1}
      # PHP-FPM optimization for ARM multithreading and concurrent requests
      - PHP_FPM_PM=${PHP_FPM_PM:-dynamic}
      - PHP_FPM_PM_MAX_CHILDREN=${PHP_FPM_PM_MAX_CHILDREN:-40}
      - PHP_FPM_PM_START_SERVERS=${PHP_FPM_PM_START_SERVERS:-8}
      - PHP_FPM_PM_MIN_SPARE_SERVERS=${PHP_FPM_PM_MIN_SPARE_SERVERS:-4}
      - PHP_FPM_PM_MAX_SPARE_SERVERS=${PHP_FPM_PM_MAX_SPARE_SERVERS:-12}
      - PHP_FPM_PM_MAX_REQUESTS=${PHP_FPM_PM_MAX_REQUESTS:-1000}
      - PHP_FPM_REQUEST_TERMINATE_TIMEOUT=${PHP_FPM_REQUEST_TERMINATE_TIMEOUT:-3600}
      - PHP_FPM_PROCESS_IDLE_TIMEOUT=${PHP_FPM_PROCESS_IDLE_TIMEOUT:-30s}
      # Apache optimization for ARM concurrent connections
      - APACHE_SERVER_LIMIT=${APACHE_SERVER_LIMIT:-16}
      - APACHE_MAX_REQUEST_WORKERS=${APACHE_MAX_REQUEST_WORKERS:-400}
      - APACHE_THREAD_LIMIT=${APACHE_THREAD_LIMIT:-25}
      - APACHE_THREADS_PER_CHILD=${APACHE_THREADS_PER_CHILD:-25}
      - APACHE_MIN_SPARE_THREADS=${APACHE_MIN_SPARE_THREADS:-25}
      - APACHE_MAX_SPARE_THREADS=${APACHE_MAX_SPARE_THREADS:-75}
      - APACHE_KEEPALIVE_TIMEOUT=${APACHE_KEEPALIVE_TIMEOUT:-5}
      - APACHE_MAX_KEEPALIVE_REQUESTS=${APACHE_MAX_KEEPALIVE_REQUESTS:-100}
    volumes:
      - "nextcloud_app_volume:/var/www/html"
      - "nextcloud_data_volume:/var/www/html/data"
    networks:
      - nextcloud_stack
      - traefik_public
    
    # Swarm mode deployment configuration
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 60s
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 10s
        failure_action: pause
        monitor: 60s
        order: stop-first
      resources:
        limits:
          cpus: '${NEXTCLOUD_CPU_LIMIT:-4.0}'
          memory: ${NEXTCLOUD_MEMORY_LIMIT:-4G}
        reservations:
          cpus: '${NEXTCLOUD_CPU_RESERVATION:-2.0}'
          memory: ${NEXTCLOUD_MEMORY_RESERVATION:-2G}
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_public"
        - "traefik.http.routers.nextcloud.rule=Host(`${DOMAIN_NAME}`)"
        - "traefik.http.routers.nextcloud.entrypoints=web,websecure"
        - "traefik.http.routers.nextcloud.tls=true"
        - "traefik.http.routers.nextcloud.tls.certresolver=letsencrypt"
        - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
        # Large file support headers
        - "traefik.http.middlewares.nextcloud-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
        - "traefik.http.middlewares.nextcloud-headers.headers.customrequestheaders.X-Forwarded-Port=443"
        - "traefik.http.middlewares.nextcloud-headers.headers.customrequestheaders.X-Forwarded-Host=${DOMAIN_NAME}"
        - "traefik.http.middlewares.nextcloud-buffering.buffering.maxRequestBodyBytes=1099511627776"  # 1TB
        - "traefik.http.middlewares.nextcloud-buffering.buffering.retryExpression=IsNetworkError() && Attempts() <= 3"
        - "traefik.http.routers.nextcloud.middlewares=nextcloud-headers,nextcloud-buffering"
    


  nextcloud_db:
    image: "postgres:16-alpine"
    environment:
      - POSTGRES_DB=${NEXTCLOUD_DB_NAME}
      - POSTGRES_USER=${NEXTCLOUD_DB_USER}
      - POSTGRES_PASSWORD=${NEXTCLOUD_DB_PASSWORD}
      - TZ=${TZ}
      # ARM-optimized PostgreSQL settings via environment
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256 --auth-local=peer
    volumes:
      - "nextcloud_db_volume:/var/lib/postgresql/data"
    networks:
      - nextcloud_stack
    # Swarm mode deployment configuration for database
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 60s
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 10s
        failure_action: pause
        monitor: 60s
        order: stop-first
      resources:
        limits:
          cpus: '${DB_CPU_LIMIT:-2.0}'
          memory: ${DB_MEMORY_LIMIT:-2G}
        reservations:
          cpus: '${DB_CPU_RESERVATION:-1.0}'
          memory: ${DB_MEMORY_RESERVATION:-1G}
    command: >
      postgres
      -c max_connections=${DB_MAX_CONNECTIONS:-300}
      -c shared_buffers=${DB_SHARED_BUFFERS:-512MB}
      -c effective_cache_size=${DB_EFFECTIVE_CACHE_SIZE:-1536MB}
      -c maintenance_work_mem=${DB_MAINTENANCE_WORK_MEM:-128MB}
      -c checkpoint_completion_target=${DB_CHECKPOINT_COMPLETION_TARGET:-0.9}
      -c wal_buffers=${DB_WAL_BUFFERS:-16MB}
      -c default_statistics_target=${DB_DEFAULT_STATISTICS_TARGET:-100}
      -c random_page_cost=${DB_RANDOM_PAGE_COST:-1.1}
      -c effective_io_concurrency=${DB_EFFECTIVE_IO_CONCURRENCY:-200}
      -c work_mem=${DB_WORK_MEM:-8MB}
      -c min_wal_size=${DB_MIN_WAL_SIZE:-2GB}
      -c max_wal_size=${DB_MAX_WAL_SIZE:-4GB}
      -c max_worker_processes=${DB_MAX_WORKER_PROCESSES:-8}
      -c max_parallel_workers_per_gather=${DB_MAX_PARALLEL_WORKERS_PER_GATHER:-4}
      -c max_parallel_workers=${DB_MAX_PARALLEL_WORKERS:-8}
      -c max_parallel_maintenance_workers=${DB_MAX_PARALLEL_MAINTENANCE_WORKERS:-4}
      -c fsync=${DB_FSYNC:-on}
      -c synchronous_commit=${DB_SYNCHRONOUS_COMMIT:-on}
      -c full_page_writes=${DB_FULL_PAGE_WRITES:-on}
      -c wal_compression=${DB_WAL_COMPRESSION:-on}
      -c checkpoint_timeout=${DB_CHECKPOINT_TIMEOUT:-5min}
      -c archive_mode=${DB_ARCHIVE_MODE:-off}
      -c log_destination=${DB_LOG_DESTINATION:-stderr}
      -c log_statement=${DB_LOG_STATEMENT:-none}
      -c log_min_duration_statement=${DB_LOG_MIN_DURATION_STATEMENT:-1000}
      -c idle_in_transaction_session_timeout=${DB_IDLE_IN_TRANSACTION_TIMEOUT:-300000}
      -c lock_timeout=${DB_LOCK_TIMEOUT:-30000}
      -c statement_timeout=${DB_STATEMENT_TIMEOUT:-300000}
      -c tcp_keepalives_idle=${DB_TCP_KEEPALIVES_IDLE:-600}
      -c tcp_keepalives_interval=${DB_TCP_KEEPALIVES_INTERVAL:-30}
      -c tcp_keepalives_count=${DB_TCP_KEEPALIVES_COUNT:-3}
    logging:
      driver: json-file
      options:
        max-file: '5'
        max-size: 10m

  nextcloud_redis:
    image: "redis:7-alpine"
    environment:
      - TZ=${TZ}
    volumes:
      - "nextcloud_redis_volume:/data"
    networks:
      - nextcloud_stack
    # Swarm mode deployment configuration for Redis
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 60s
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 10s
        failure_action: pause
        monitor: 60s
        order: stop-first
      resources:
        limits:
          cpus: '${REDIS_CPU_LIMIT:-1.0}'
          memory: ${REDIS_MEMORY_LIMIT:-1G}
        reservations:
          cpus: '${REDIS_CPU_RESERVATION:-0.5}'
          memory: ${REDIS_MEMORY_RESERVATION:-512M}
    command: >
      redis-server
      --requirepass ${NEXTCLOUD_REDIS_PASSWORD}
      --maxmemory ${REDIS_MAXMEMORY:-768mb}
      --maxmemory-policy ${REDIS_MAXMEMORY_POLICY:-allkeys-lru}
      --tcp-keepalive ${REDIS_TCP_KEEPALIVE:-60}
      --tcp-backlog ${REDIS_TCP_BACKLOG:-1024}
      --timeout ${REDIS_TIMEOUT:-0}
      --maxclients ${REDIS_MAX_CLIENTS:-1000}
      --databases ${REDIS_DATABASES:-16}
      --save ${REDIS_SAVE_900:-900} ${REDIS_SAVE_900_CHANGES:-1}
      --save ${REDIS_SAVE_300:-300} ${REDIS_SAVE_300_CHANGES:-10}
      --save ${REDIS_SAVE_60:-60} ${REDIS_SAVE_60_CHANGES:-10000}
      --rdbcompression ${REDIS_RDB_COMPRESSION:-yes}
      --rdbchecksum ${REDIS_RDB_CHECKSUM:-yes}
      --stop-writes-on-bgsave-error ${REDIS_STOP_WRITES_ON_BGSAVE_ERROR:-yes}
      --lazyfree-lazy-eviction ${REDIS_LAZYFREE_LAZY_EVICTION:-yes}
      --lazyfree-lazy-expire ${REDIS_LAZYFREE_LAZY_EXPIRE:-yes}
      --lazyfree-lazy-server-del ${REDIS_LAZYFREE_LAZY_SERVER_DEL:-yes}
      --replica-lazy-flush ${REDIS_REPLICA_LAZY_FLUSH:-yes}
      --io-threads ${REDIS_IO_THREADS:-4}
      --io-threads-do-reads ${REDIS_IO_THREADS_DO_READS:-yes}
    logging:
      driver: json-file
      options:
        max-file: '5'
        max-size: 10m



networks:
  # Internal overlay network for stack communication
  nextcloud_stack:
    driver: overlay
    driver_opts:
      com.docker.network.driver.mtu: 1500
    internal: false
    attachable: true

  # External Traefik public network for proxy communication
  traefik_public:
    external: true
    name: "traefik_public"

volumes:
  # Nextcloud application volume (includes config, apps, etc.)
  nextcloud_app_volume:
    name: "${CONTAINER_NAME_PREFIX}_nextcloud_app"
    driver: local
    driver_opts:
      type: ${CONFIG_VOLUME_TYPE:-none}
      o: ${CONFIG_VOLUME_OPTIONS:-bind,rw,noatime}
      device: ${CONFIG_BASE}/nextcloud/app

  # Nextcloud data volume (user files) - optimized for large files
  nextcloud_data_volume:
    name: "${CONTAINER_NAME_PREFIX}_nextcloud_data"
    driver: local
    driver_opts:
      type: ${DATA_VOLUME_TYPE:-none}
      o: ${DATA_VOLUME_OPTIONS:-bind,rw,noatime,async}
      device: ${DATA_BASE}/nextcloud

  # PostgreSQL database volume
  nextcloud_db_volume:
    name: "${CONTAINER_NAME_PREFIX}_nextcloud_db"
    driver: local
    driver_opts:
      type: ${CONFIG_VOLUME_TYPE:-none}
      o: ${CONFIG_VOLUME_OPTIONS:-bind,rw,noatime}
      device: ${CONFIG_BASE}/nextcloud/db

  # Redis cache volume
  nextcloud_redis_volume:
    name: "${CONTAINER_NAME_PREFIX}_nextcloud_redis"
    driver: local
    driver_opts:
      type: ${CONFIG_VOLUME_TYPE:-none}
      o: ${CONFIG_VOLUME_OPTIONS:-bind,rw,noatime}
      device: ${CONFIG_BASE}/nextcloud/redis
