# This is the Nextcloud configuration file that creates local volumes for all containers.
# Environment variables are loaded from .env file by default
# See README.md for detailed documentation
#
# This setup includes:
# - Nextcloud web application (Official image with auto-configuration)
# - PostgreSQL database
# - Redis cache

version: "3.8"

services:
  nextcloud:
    container_name: "${CONTAINER_NAME_PREFIX}_nextcloud"
    image: "nextcloud:latest"
    environment:
      - TZ=${TZ}
      # Database configuration
      - POSTGRES_DB=${NEXTCLOUD_DB_NAME}
      - POSTGRES_USER=${NEXTCLOUD_DB_USER}
      - POSTGRES_PASSWORD=${NEXTCLOUD_DB_PASSWORD}
      - POSTGRES_HOST=nextcloud_db:5432
      # Admin user configuration
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      # Redis configuration
      - REDIS_HOST=nextcloud_redis
      - REDIS_HOST_PASSWORD=${NEXTCLOUD_REDIS_PASSWORD}
      # Trusted domains
      - NEXTCLOUD_TRUSTED_DOMAINS=${DOMAIN_NAME}
      # Data directory
      - NEXTCLOUD_DATA_DIR=/var/www/html/data
      # Reverse proxy configuration
      - OVERWRITEPROTOCOL=https
      - OVERWRITEHOST=${DOMAIN_NAME}
      - TRUSTED_PROXIES=172.16.0.0/12
    volumes:
      - "nextcloud_app_volume:/var/www/html"
      - "nextcloud_data_volume:/var/www/html/data"
    networks:
      - nextcloud_apps
      - nextcloud_database_network
      - container_internet
    depends_on:
      - nextcloud_db
      - nextcloud_redis
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.nextcloud.entrypoints=web,websecure"
      - "traefik.http.routers.nextcloud.tls=true"
      - "traefik.http.routers.nextcloud.tls.certresolver=letsencrypt"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
      # Nextcloud specific headers
      - "traefik.http.middlewares.nextcloud-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.nextcloud-headers.headers.customrequestheaders.X-Forwarded-Port=443"
      - "traefik.http.middlewares.nextcloud-headers.headers.customrequestheaders.X-Forwarded-Host=${DOMAIN_NAME}"
      - "traefik.http.routers.nextcloud.middlewares=nextcloud-headers"

  nextcloud_db:
    container_name: "${CONTAINER_NAME_PREFIX}_nextcloud_db"
    image: "postgres:16-alpine"
    environment:
      - POSTGRES_DB=${NEXTCLOUD_DB_NAME}
      - POSTGRES_USER=${NEXTCLOUD_DB_USER}
      - POSTGRES_PASSWORD=${NEXTCLOUD_DB_PASSWORD}
      - TZ=${TZ}
    volumes:
      - "nextcloud_db_volume:/var/lib/postgresql/data"
    networks:
      - nextcloud_database_network
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-file: '5'
        max-size: 10m

  nextcloud_redis:
    container_name: "${CONTAINER_NAME_PREFIX}_nextcloud_redis"
    image: "redis:7-alpine"
    environment:
      - TZ=${TZ}
    volumes:
      - "nextcloud_redis_volume:/data"
    networks:
      - nextcloud_database_network
    restart: unless-stopped
    command: redis-server --requirepass ${NEXTCLOUD_REDIS_PASSWORD}
    logging:
      driver: json-file
      options:
        max-file: '5'
        max-size: 10m



networks:
  # Internal isolated network for inter-service communication
  nextcloud_apps:
    name: "${NEXTCLOUD_NETWORK}"
    internal: true
    driver: bridge

  # Database network for database communication
  nextcloud_database_network:
    name: "${CONTAINER_NAME_PREFIX}_nextcloud_db_network"
    internal: true
    driver: bridge

  # External network for internet access
  container_internet:
    external: true
    name: "containers_internet"

volumes:
  # Nextcloud application volume (includes config, apps, etc.)
  nextcloud_app_volume:
    name: "${CONTAINER_NAME_PREFIX}_nextcloud_app"
    driver: local
    driver_opts:
      type: ${CONFIG_VOLUME_TYPE:-}
      o: ${CONFIG_VOLUME_OPTIONS:-}
      device: ${CONFIG_BASE}/nextcloud/app

  # Nextcloud data volume (user files)
  nextcloud_data_volume:
    name: "${CONTAINER_NAME_PREFIX}_nextcloud_data"
    driver: local
    driver_opts:
      type: ${DATA_VOLUME_TYPE:-}
      o: ${DATA_VOLUME_OPTIONS:-}
      device: ${DATA_BASE}/nextcloud

  # PostgreSQL database volume
  nextcloud_db_volume:
    name: "${CONTAINER_NAME_PREFIX}_nextcloud_db"
    driver: local
    driver_opts:
      type: ${CONFIG_VOLUME_TYPE:-}
      o: ${CONFIG_VOLUME_OPTIONS:-}
      device: ${CONFIG_BASE}/nextcloud/db

  # Redis cache volume
  nextcloud_redis_volume:
    name: "${CONTAINER_NAME_PREFIX}_nextcloud_redis"
    driver: local
    driver_opts:
      type: ${CONFIG_VOLUME_TYPE:-}
      o: ${CONFIG_VOLUME_OPTIONS:-}
      device: ${CONFIG_BASE}/nextcloud/redis