apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: nextcloud-data-volume
  name: nextcloud-data-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Gi
