apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: nextcloud-db
  name: nextcloud-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nextcloud-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml convert
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: nextcloud-db
    spec:
      containers:
        - args:
            - postgres
            - -c
            - max_connections=300
            - -c
            - shared_buffers=512MB
            - -c
            - effective_cache_size=1536MB
            - -c
            - maintenance_work_mem=128MB
            - -c
            - checkpoint_completion_target=0.9
            - -c
            - wal_buffers=16MB
            - -c
            - default_statistics_target=100
            - -c
            - random_page_cost=1.1
            - -c
            - effective_io_concurrency=200
            - -c
            - work_mem=8MB
            - -c
            - min_wal_size=2GB
            - -c
            - max_wal_size=4GB
            - -c
            - max_worker_processes=8
            - -c
            - max_parallel_workers_per_gather=4
            - -c
            - max_parallel_workers=8
            - -c
            - max_parallel_maintenance_workers=4
            - -c
            - fsync=on
            - -c
            - synchronous_commit=on
            - -c
            - full_page_writes=on
            - -c
            - wal_compression=on
            - -c
            - checkpoint_timeout=5min
            - -c
            - archive_mode=off
            - -c
            - log_destination=stderr
            - -c
            - log_statement=none
            - -c
            - log_min_duration_statement=1000
            - -c
            - idle_in_transaction_session_timeout=300000
            - -c
            - lock_timeout=30000
            - -c
            - statement_timeout=300000
            - -c
            - tcp_keepalives_idle=600
            - -c
            - tcp_keepalives_interval=30
            - -c
            - tcp_keepalives_count=3
          env:
            - name: POSTGRES_DB
            - name: POSTGRES_INITDB_ARGS
              value: --auth-host=scram-sha-256 --auth-local=peer
            - name: POSTGRES_PASSWORD
            - name: POSTGRES_USER
            - name: TZ
          image: postgres:16-alpine
          name: -nextcloud-db
          resources:
            limits:
              cpu: "2"
              memory: "2147483648"
            requests:
              cpu: "1"
              memory: "1073741824"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: nextcloud-db-volume
      restartPolicy: Always
      volumes:
        - name: nextcloud-db-volume
          persistentVolumeClaim:
            claimName: nextcloud-db-volume
