apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: nextcloud
  name: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nextcloud
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml convert
        kompose.version: 1.36.0 (HEAD)
        # Traefik Ingress Controller Configuration
        traefik.enable: "true"
        # Router configuration
        traefik.http.routers.nextcloud.rule: "Host(`nextcloud.local`)"
        traefik.http.routers.nextcloud.entrypoints: "web,websecure"
        traefik.http.routers.nextcloud.tls: "true"
        traefik.http.routers.nextcloud.tls.certresolver: "letsencrypt"
        # Service configuration
        traefik.http.services.nextcloud.loadbalancer.server.port: "80"
        # Middleware configuration for headers
        traefik.http.middlewares.nextcloud-headers.headers.customrequestheaders.X-Forwarded-Proto: "https"
        traefik.http.middlewares.nextcloud-headers.headers.customrequestheaders.X-Forwarded-Port: "443"
        traefik.http.middlewares.nextcloud-headers.headers.customrequestheaders.X-Forwarded-Host: "nextcloud.local"
        # Middleware configuration for large file support
        traefik.http.middlewares.nextcloud-buffering.buffering.maxRequestBodyBytes: "1099511627776"
        traefik.http.middlewares.nextcloud-buffering.buffering.retryExpression: "IsNetworkError() && Attempts() <= 3"
        # Apply middlewares to router
        traefik.http.routers.nextcloud.middlewares: "nextcloud-headers,nextcloud-buffering"
      labels:
        io.kompose.service: nextcloud
    spec:
      containers:
        - env:
            - name: APACHE_BODY_LIMIT
              value: "1073741824000"
            - name: APACHE_KEEPALIVE_TIMEOUT
              value: "5"
            - name: APACHE_MAX_KEEPALIVE_REQUESTS
              value: "100"
            - name: APACHE_MAX_REQUEST_WORKERS
              value: "400"
            - name: APACHE_MAX_SPARE_THREADS
              value: "75"
            - name: APACHE_MIN_SPARE_THREADS
              value: "25"
            - name: APACHE_SERVER_LIMIT
              value: "16"
            - name: APACHE_THREADS_PER_CHILD
              value: "25"
            - name: APACHE_THREAD_LIMIT
              value: "25"
            - name: NEXTCLOUD_ADMIN_PASSWORD
            - name: NEXTCLOUD_ADMIN_USER
            - name: NEXTCLOUD_DATA_DIR
              value: /var/www/html/data
            - name: NEXTCLOUD_TRUSTED_DOMAINS
            - name: OVERWRITEHOST
            - name: OVERWRITEPROTOCOL
              value: https
            - name: PHP_FPM_PM
              value: dynamic
            - name: PHP_FPM_PM_MAX_CHILDREN
              value: "40"
            - name: PHP_FPM_PM_MAX_REQUESTS
              value: "1000"
            - name: PHP_FPM_PM_MAX_SPARE_SERVERS
              value: "12"
            - name: PHP_FPM_PM_MIN_SPARE_SERVERS
              value: "4"
            - name: PHP_FPM_PM_START_SERVERS
              value: "8"
            - name: PHP_FPM_PROCESS_IDLE_TIMEOUT
              value: 30s
            - name: PHP_FPM_REQUEST_TERMINATE_TIMEOUT
              value: "3600"
            - name: PHP_MAX_EXECUTION_TIME
              value: "3600"
            - name: PHP_MAX_FILE_UPLOADS
              value: "200"
            - name: PHP_MAX_INPUT_TIME
              value: "3600"
            - name: PHP_MAX_INPUT_VARS
              value: "10000"
            - name: PHP_MEMORY_LIMIT
              value: 2G
            - name: PHP_OPCACHE_ENABLE
              value: "1"
            - name: PHP_OPCACHE_MAX_ACCELERATED_FILES
              value: "10000"
            - name: PHP_OPCACHE_MEMORY_CONSUMPTION
              value: "256"
            - name: PHP_OPCACHE_REVALIDATE_FREQ
              value: "1"
            - name: PHP_OPCACHE_SAVE_COMMENTS
              value: "1"
            - name: PHP_POST_MAX_SIZE
              value: 1024G
            - name: PHP_UPLOAD_LIMIT
              value: 1024G
            - name: POSTGRES_DB
            - name: POSTGRES_HOST
              value: nextcloud_db:5432
            - name: POSTGRES_PASSWORD
            - name: POSTGRES_USER
            - name: REDIS_HOST
              value: nextcloud_redis
            - name: REDIS_HOST_PASSWORD
            - name: TRUSTED_PROXIES
              value: 172.16.0.0/12
            - name: TZ
          image: nextcloud:latest
          name: nextcloud
          resources:
            limits:
              cpu: "4"
              memory: "4294967296"
            requests:
              cpu: "2"
              memory: "2147483648"
          volumeMounts:
            - mountPath: /var/www/html
              name: nextcloud-app-volume
            - mountPath: /var/www/html/data
              name: nextcloud-data-volume
      restartPolicy: Always
      volumes:
        - name: nextcloud-app-volume
          persistentVolumeClaim:
            claimName: nextcloud-app-volume
        - name: nextcloud-data-volume
          persistentVolumeClaim:
            claimName: nextcloud-data-volume
